CREATE TABLE consumption_primary_restructure AS
SELECT
    year,
    region,
    consumptionAgricultureMT,
    consumptionConstructionMT,
    consumptionElectronicMT,
    consumptionHouseholdLeisureSportsMT,
    consumptionPackagingMT,
    consumptionTransportationMT,
    consumptionTextileMT,
    consumptionOtherMT,
    eolRecyclingPercent,
    eolIncinerationPercent,
    eolLandfillPercent,
    eolMismanagedPercent,
    netImportArticlesMT,
    netImportFibersMT,
    netImportGoodsMT,
    netImportResinMT,
    netWasteTradeMT
FROM
    consumption_primary_restructure_no_historic
