name: Build
on: [push]

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Load R
        uses: r-lib/actions/setup-r@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2