name: Build
on: [push]

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Load R
        uses: r-lib/actions/setup-r@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Get data
        run: wget --user ${{ secrets.DOWNLOADUSER }} --password ${{ secrets.DOWNLOADPASS }} ${{ secrets.DOWNLOADURL }}
      - name: Extract data
        run: unzip 02_Data_Raw.zip
      - name: Build
        run: Rscript transform.r
