name: Pipeline
on: [push]

jobs:
  sqlpipeline:
    runs-on: ubuntu-latest
    name: SQL Pipeline
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Sqlite
        run: sudo apt install sqlite3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install other dependencies
        run: pip install -r requirements.txt
      - name: Execute
        run: bash build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Pipeline Result
          path: output
      - name: Check output
        run: bash confirm_output.sh
#  deploy:
#    runs-on: ubuntu-latest
#    environment: deploy
#    name: Deploy
#    if: github.ref == 'refs/heads/main'
#    needs: [rpipeline, sqlpipeline]
#    steps:
#      - name: Trigger
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.CROSS_TOKEN }}
#          repository: SchmidtDSE/plastics-prototype
#          event-type: data-update
