name: Pipeline
on: [push]

jobs:
  rpipeline:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
      - name: Install Sqlite
        run: sudo apt install sqlite3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Load R
        uses: r-lib/actions/setup-r@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Prepare R pipeline
        run: cd r; bash transform.sh
      - name: Run R pipeline
        run: cd r; Rscript pipeline.R
      - name: Run SQL pipeline
        run: cd sql; bash make.sh
      #- name: Run output checks
      #  run: python python/check_output.py output/overview.csv
      - uses: actions/upload-artifact@v3
        with:
          name: Pipeline Result
          path: output
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [rpipeline]
    steps:
      - name: Trigger
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CROSS_TOKEN }}
          repository: SchmidtDSE/plastics-prototype
          event-type: data-update
