name: Pipeline
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Sqlite
        run: sudo apt install sqlite3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install checks
        run: pip install pycodestyle pyflakes nose2
      - name: Install other dependencies
        run: pip install -r requirements.txt
      - name: Run pyflakes
        run: pyflakes *.py
      - name: Run pycodestyle
        run: pycodestyle *.py
      - name: Run tests
        run: nose2
  pipeline:
    runs-on: ubuntu-latest
    name: Checks
    needs: [checks]
    if: github.ref == 'refs/heads/deploy' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Sqlite
        run: sudo apt install sqlite3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install other dependencies
        run: pip install -r requirements.txt
      - name: Execute
        run: bash build.sh
      - name: Zip pipeline
        run: zip -r pipeline.zip output
      - uses: actions/upload-artifact@v3
        with:
          name: pipeline-result
          path: pipeline.zip
      - name: Check output
        run: bash confirm_output.sh
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    name: Deploy
    if: github.ref == 'refs/heads/deploy'
    needs: [pipeline]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pipeline-result
      - name: Upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './pipeline.zip'
          remotePath: './global-plastics-tool.org/data'
      - name: Trigger
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CROSS_TOKEN }}
          repository: SchmidtDSE/plastics-ghg-pipeline
          event-type: data-update
