name: Pipeline
on: [push]

jobs:
  rpipeline:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
      - name: Load R
        uses: r-lib/actions/setup-r@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build
        run: cd r; bash transform.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Pipeline Result
          path: output
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [rpipeline]
    steps:
      - name: Trigger
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CROSS_TOKEN }}
          repository: SchmidtDSE/plastics-prototype
          event-type: data-update
