name: R Pipeline
on: [push]

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    name: R Pipeline
    steps:
      - name: Load R
        uses: r-lib/actions/setup-r@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Get data
        run: wget --user ${{ secrets.DOWNLOADUSER }} --password ${{ secrets.DOWNLOADPASS }} ${{ secrets.DOWNLOADURL }}
      - name: Extract data
        run: unzip 02_Data_Raw.zip
      - name: Build
        run: cd r; Rscript transform.r
      - uses: actions/upload-artifact@v3
        with:
          name: R Pipeline Result
          path: output_r