name: SQL Pipeline
on: [push]

jobs:
  test:
    environment: build
    runs-on: ubuntu-latest
    name: SQL Pipeline
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get main data
        run: wget --user ${{ secrets.DOWNLOADUSER }} --password ${{ secrets.DOWNLOADPASS }} ${{ secrets.DOWNLOADURL }}
      - name: Extract data
        run: unzip 02_Data_Raw.zip
      - name: Install Sqlite
        run: sudo apt install sqlite3
      - name: Build database
        run: cd sql; bash make.sh
      - uses: actions/upload-artifact@v3
        with:
          name: SQL Pipeline Result
          path: output_sql
